"""
HTML Exporter

Export analysis results to interactive HTML format.
"""

from datetime import datetime
from pathlib import Path

from src.core.analyzer import AnalysisResult
from src.core.models import SuspicionLevel
from src.exporters.base import BaseExporter
from src.utils.config import OutputConfig
from src.utils.i18n import I18nManager


class HTMLExporter(BaseExporter):
    """Export analysis results to HTML format."""
    
    # Suspicion level color classes
    SUSPICION_CLASSES = {
        SuspicionLevel.CRITICAL: "severity-critical",
        SuspicionLevel.HIGH: "severity-high",
        SuspicionLevel.MEDIUM: "severity-moderate",
        SuspicionLevel.LOW: "severity-low",
    }
    
    def __init__(
        self,
        output_config: OutputConfig,
        i18n: I18nManager | None = None,
        include_charts: bool = True
    ):
        """
        Initialize HTML exporter.
        
        Args:
            output_config: Output configuration
            i18n: Internationalization manager
            include_charts: Whether to include Chart.js visualizations
        """
        super().__init__(output_config, i18n)
        self.include_charts = include_charts
    
    @property
    def file_extension(self) -> str:
        return "html"
    
    @property
    def name(self) -> str:
        return "HTML"
    
    def export(
        self,
        result: AnalysisResult,
        output_path: Path | str | None = None
    ) -> Path:
        """Export single analysis result to HTML."""
        return self.export_multiple([result], output_path)
    
    def export_multiple(
        self,
        results: list[AnalysisResult],
        output_path: Path | str | None = None
    ) -> Path:
        """Export multiple analysis results to HTML."""
        if output_path:
            path = Path(output_path)
        else:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            path = self._get_output_path(f"mal_bombing_report_{timestamp}")
        
        # Build HTML content
        html = self._build_html(results)
        
        # Write to file
        path.parent.mkdir(parents=True, exist_ok=True)
        
        with open(path, "w", encoding="utf-8") as f:
            f.write(html)
        
        return path
    
    def _build_html(self, results: list[AnalysisResult]) -> str:
        """Build complete HTML document."""
        return f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{self._translate("export.html.title")}</title>
    {self._get_styles()}
    {self._get_chart_scripts() if self.include_charts else ""}
</head>
<body>
    <div class="container">
        <header>
            <h1>{self._translate("export.html.title")}</h1>
            <p class="subtitle">{self._translate("export.html.generated_at")}: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </header>
        
        <section class="summary">
            <h2>{self._translate("export.html.summary")}</h2>
            {self._build_summary_html(results)}
        </section>
        
        {self._build_charts_html(results) if self.include_charts else ""}
        
        <section class="results">
            <h2>{self._translate("export.html.results")}</h2>
            {self._build_table_html(results)}
        </section>
        
        <footer>
            <p>Generated by MAL Bombing Detector v1.0</p>
        </footer>
    </div>
    
    {self._get_chart_init_scripts(results) if self.include_charts else ""}
</body>
</html>"""
    
    def _get_styles(self) -> str:
        """Get CSS styles."""
        return """<style>
    :root {
        --color-critical: #dc3545;
        --color-high: #fd7e14;
        --color-moderate: #ffc107;
        --color-low: #28a745;
        --color-minimal: #20c997;
        --color-none: #6c757d;
    }
    
    * {
        box-sizing: border-box;
        margin: 0;
        padding: 0;
    }
    
    body {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        line-height: 1.6;
        color: #333;
        background: #f5f5f5;
    }
    
    .container {
        max-width: 1400px;
        margin: 0 auto;
        padding: 20px;
    }
    
    header {
        text-align: center;
        padding: 40px 20px;
        background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
        color: white;
        border-radius: 10px;
        margin-bottom: 30px;
    }
    
    header h1 {
        font-size: 2.5rem;
        margin-bottom: 10px;
    }
    
    .subtitle {
        opacity: 0.9;
    }
    
    section {
        background: white;
        border-radius: 10px;
        padding: 30px;
        margin-bottom: 30px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.1);
    }
    
    h2 {
        color: #667eea;
        margin-bottom: 20px;
        padding-bottom: 10px;
        border-bottom: 2px solid #eee;
    }
    
    .summary-grid {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 20px;
    }
    
    .summary-card {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
        text-align: center;
    }
    
    .summary-card .value {
        font-size: 2rem;
        font-weight: bold;
        color: #667eea;
    }
    
    .summary-card .label {
        color: #666;
        font-size: 0.9rem;
    }
    
    .charts-container {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
        gap: 30px;
    }
    
    .chart-wrapper {
        background: #f8f9fa;
        padding: 20px;
        border-radius: 8px;
    }
    
    table {
        width: 100%;
        border-collapse: collapse;
        font-size: 0.9rem;
    }
    
    th, td {
        padding: 12px 15px;
        text-align: left;
        border-bottom: 1px solid #eee;
    }
    
    th {
        background: #667eea;
        color: white;
        font-weight: 600;
        position: sticky;
        top: 0;
    }
    
    tr:hover {
        background: #f8f9fa;
    }
    
    .severity-badge {
        padding: 4px 12px;
        border-radius: 20px;
        font-size: 0.8rem;
        font-weight: 600;
        color: white;
    }
    
    .severity-critical { background: var(--color-critical); }
    .severity-high { background: var(--color-high); }
    .severity-moderate { background: var(--color-moderate); color: #333; }
    .severity-low { background: var(--color-low); }
    .severity-minimal { background: var(--color-minimal); }
    .severity-none { background: var(--color-none); }
    
    .score-bar {
        height: 8px;
        background: #eee;
        border-radius: 4px;
        overflow: hidden;
    }
    
    .score-bar-fill {
        height: 100%;
        background: linear-gradient(90deg, #28a745, #ffc107, #dc3545);
        border-radius: 4px;
    }
    
    footer {
        text-align: center;
        padding: 20px;
        color: #666;
        font-size: 0.9rem;
    }
    
    @media (max-width: 768px) {
        header h1 {
            font-size: 1.8rem;
        }
        
        table {
            font-size: 0.8rem;
        }
        
        th, td {
            padding: 8px 10px;
        }
    }
</style>"""
    
    def _get_chart_scripts(self) -> str:
        """Get Chart.js script tags."""
        return """<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>"""
    
    def _build_summary_html(self, results: list[AnalysisResult]) -> str:
        """Build summary section HTML."""
        # Aggregate all metrics from all results
        all_metrics = []
        for r in results:
            all_metrics.extend(r.metrics)
        
        total = len(all_metrics)
        
        # Count by suspicion level
        level_counts = {level: 0 for level in SuspicionLevel}
        for m in all_metrics:
            level_counts[m.suspicion_level] += 1
        
        avg_score = sum(m.bombing_score for m in all_metrics) / total if total > 0 else 0
        
        return f"""<div class="summary-grid">
    <div class="summary-card">
        <div class="value">{total}</div>
        <div class="label">Total Analyzed</div>
    </div>
    <div class="summary-card">
        <div class="value" style="color: var(--color-critical);">{level_counts[SuspicionLevel.CRITICAL]}</div>
        <div class="label">Critical</div>
    </div>
    <div class="summary-card">
        <div class="value" style="color: var(--color-high);">{level_counts[SuspicionLevel.HIGH]}</div>
        <div class="label">High</div>
    </div>
    <div class="summary-card">
        <div class="value" style="color: var(--color-moderate);">{level_counts[SuspicionLevel.MEDIUM]}</div>
        <div class="label">Medium</div>
    </div>
    <div class="summary-card">
        <div class="value">{avg_score:.2f}</div>
        <div class="label">Avg Bombing Score</div>
    </div>
</div>"""
    
    def _build_charts_html(self, results: list[AnalysisResult]) -> str:
        """Build charts section HTML."""
        return """<section class="charts">
    <h2>Visualizations</h2>
    <div class="charts-container">
        <div class="chart-wrapper">
            <canvas id="severityChart"></canvas>
        </div>
        <div class="chart-wrapper">
            <canvas id="suspicionChart"></canvas>
        </div>
    </div>
</section>"""
    
    def _build_table_html(self, results: list[AnalysisResult]) -> str:
        """Build results table HTML."""
        rows = []
        
        for r in results:
            anime = r.anime
            metrics = r.metrics
            severity_class = self.SEVERITY_CLASSES[metrics.severity]
            
            rows.append(f"""<tr>
    <td>{anime.rank}</td>
    <td><a href="{anime.url}" target="_blank">{anime.title}</a></td>
    <td>{anime.score}</td>
    <td>{anime.members:,}</td>
    <td>{metrics.suspicion_score:.2f}</td>
    <td><span class="severity-badge {severity_class}">{metrics.severity.value}</span></td>
    <td>{metrics.ones_percent:.1f}%</td>
    <td>{metrics.tens_percent:.1f}%</td>
</tr>""")
        
        return f"""<div style="overflow-x: auto;">
<table>
    <thead>
        <tr>
            <th>Rank</th>
            <th>Title</th>
            <th>Score</th>
            <th>Members</th>
            <th>Suspicion</th>
            <th>Severity</th>
            <th>1s %</th>
            <th>10s %</th>
        </tr>
    </thead>
    <tbody>
        {"".join(rows)}
    </tbody>
</table>
</div>"""
    
    def _get_chart_init_scripts(self, results: list[AnalysisResult]) -> str:
        """Get Chart.js initialization scripts."""
        # Aggregate all metrics
        all_metrics = []
        for r in results:
            all_metrics.extend(r.metrics)
        
        # Suspicion level distribution data
        level_counts = {level.value: 0 for level in SuspicionLevel}
        for m in all_metrics:
            level_counts[m.suspicion_level.value] += 1
        
        # Top 10 suspicious
        top_suspicious = sorted(all_metrics, key=lambda m: m.bombing_score, reverse=True)[:10]
        top_labels = [m.title[:25] for m in top_suspicious]
        top_values = [m.bombing_score for m in top_suspicious]
        
        return f"""<script>
// Suspicion Level Distribution Chart
new Chart(document.getElementById('severityChart'), {{
    type: 'doughnut',
    data: {{
        labels: {list(level_counts.keys())},
        datasets: [{{
            data: {list(level_counts.values())},
            backgroundColor: [
                '#dc3545', '#fd7e14', '#ffc107', '#28a745'
            ]
        }}]
    }},
    options: {{
        responsive: true,
        plugins: {{
            title: {{
                display: true,
                text: 'Suspicion Level Distribution'
            }}
        }}
    }}
}});

// Top Suspicious Chart
new Chart(document.getElementById('suspicionChart'), {{
    type: 'bar',
    data: {{
        labels: {top_labels},
        datasets: [{{
            label: 'Bombing Score',
            data: {top_values},
            backgroundColor: '#667eea'
        }}]
    }},
    options: {{
        responsive: true,
        indexAxis: 'y',
        plugins: {{
            title: {{
                display: true,
                text: 'Top Suspicious Anime'
            }}
        }}
    }}
}});
</script>"""
